
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:80"  # Вы можете оставить это, чтобы тестировать приложение отдельно, но Nginx будет использовать внутреннюю связь
    restart: always
    networks:
      - frontend-network


networks:
  frontend-network:
    driver: bridge
